[delegacy-rpz]
fetch.git = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git"
src.git = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git"

[firefox-translations-models]
fetch.github = "mozilla/firefox-translations-models"
git.fetchSubmodules = true # Force use fetchgit
src.git = "https://github.com/mozilla/firefox-translations-models.git"

[grafana-falconlogscale-datasource]
fetch.url = "https://github.com/grafana/falconlogscale-datasource/releases/download/v$ver/grafana-falconlogscale-datasource-$ver.zip"
src.github = "grafana/falconlogscale-datasource"
src.prefix = "v"

[grafana-yesoreyeram-infinity-datasource]
fetch.url = "https://github.com/grafana/grafana-infinity-datasource/releases/download/v$ver/yesoreyeram-infinity-datasource-$ver.zip"
src.github = "grafana/grafana-infinity-datasource"
src.prefix = "v"

[lobe-icons]
fetch.git = "https://github.com/lobehub/lobe-icons.git"
src.git = "https://github.com/lobehub/lobe-icons.git"

[mihoyo-bbs-tools]
fetch.github = "Womsxd/MihoyoBBSTools"
src.git = "https://github.com/Womsxd/MihoyoBBSTools.git"

[mpv-sockets]
fetch.github = "wis/mpvSockets"
src.git = "https://github.com/wis/mpvSockets.git"

[nix-ubw]
fetch.github = "xddxdd/nix-ubw"
src.git = "git@github.com:xddxdd/nix-ubw.git"

[nvidia-patch]
fetch.github = "keylase/nvidia-patch"
src.git = "https://github.com/keylase/nvidia-patch.git"

[ohmyzsh-tirith]
fetch.github = "sheeki03/ohmyzsh-tirith"
src.git = "https://github.com/sheeki03/ohmyzsh-tirith.git"

[open5gs]
fetch.github = "open5gs/open5gs"
src.github = "open5gs/open5gs"

[open5gs-freediameter]
fetch.github = "open5gs/freeDiameter"
src.git = "https://github.com/open5gs/freeDiameter.git"
src.branch = "r1.5.0"

[openspeedtest]
fetch.github = "openspeedtest/Speed-Test"
src.git = "https://github.com/openspeedtest/Speed-Test.git"

[sakura-share]
fetch.github = "xddxdd/Sakura_Launcher_GUI"
src.git = "https://github.com/xddxdd/Sakura_Launcher_GUI.git"

[ulauncher-albert-calculate-anything]
fetch.github = "tchar/ulauncher-albert-calculate-anything"
src.git = "https://github.com/tchar/ulauncher-albert-calculate-anything.git"

[ulauncher-antigravity-launcher]
fetch.github = "TheFury-BOY/antigravity-ulauncher"
src.git = "https://github.com/TheFury-BOY/antigravity-ulauncher.git"

[ulauncher-chrome-profiles]
fetch.github = "FloydJohn/ulauncher-chrome-profiles"
src.git = "https://github.com/FloydJohn/ulauncher-chrome-profiles.git"

[ulauncher-colorconverter]
fetch.github = "sergius02/ulauncher-colorconverter"
src.git = "https://github.com/sergius02/ulauncher-colorconverter.git"

[ulauncher-cursor-projects]
fetch.github = "rlvendramini/ulauncher-cursor-projects-ext"
src.git = "https://github.com/rlvendramini/ulauncher-cursor-projects-ext.git"

[ulauncher-emoji]
fetch.github = "Ulauncher/ulauncher-emoji"
src.git = "https://github.com/Ulauncher/ulauncher-emoji.git"

[ulauncher-extension-list]
fetch.github = "ralcaidev/ulauncher-extension-list"
src.git = "https://github.com/ralcaidev/ulauncher-extension-list.git"

[ulauncher-faker]
fetch.github = "brpaz/ulauncher-faker"
src.git = "https://github.com/brpaz/ulauncher-faker.git"

[ulauncher-firefox-launcher]
fetch.github = "freisatz/ulauncher-firefox-launcher"
src.git = "https://github.com/freisatz/ulauncher-firefox-launcher.git"

[ulauncher-kill]
fetch.github = "Ulauncher/ulauncher-kill"
src.git = "https://github.com/Ulauncher/ulauncher-kill.git"

[ulauncher-meme-my-text]
fetch.github = "RNairn01/ulauncher-meme-my-text"
src.git = "https://github.com/RNairn01/ulauncher-meme-my-text.git"

[ulauncher-pwgen]
fetch.github = "brpaz/ulauncher-pwgen"
src.git = "https://github.com/brpaz/ulauncher-pwgen.git"

[ulauncher-timestamp]
fetch.github = "brpaz/ulauncher-timestamp"
src.git = "https://github.com/brpaz/ulauncher-timestamp.git"

[ulauncher-timezone]
fetch.github = "Epholys/ultz"
src.git = "https://github.com/Epholys/ultz.git"

[ulauncher-tldr]
fetch.github = "dhelmr/ulauncher-tldr"
src.git = "https://github.com/dhelmr/ulauncher-tldr.git"

[ulauncher-vscode-recent]
fetch.github = "plibither8/ulauncher-vscode-recent"
src.git = "https://github.com/plibither8/ulauncher-vscode-recent.git"

[um-react]
fetch.url = "https://git.um-react.app/um/um-react/releases/download/v$ver/um-react-$ver.zip"
src.webpage = "https://git.um-react.app/um/um-react/releases"
src.regex = "href=\"/um/um-react/src/tag/v([0-9\\.]+)\""

[yourls]
fetch.github = "YOURLS/YOURLS"
src.github = "YOURLS/YOURLS"

[yourls-404-if-not-found]
fetch.github = "YOURLS/404-if-not-found"
src.git = "https://github.com/YOURLS/404-if-not-found.git"

[yourls-always-302]
fetch.github = "tinjaw/Always-302"
src.git = "https://github.com/tinjaw/Always-302.git"

[yourls-dont-track-admins]
fetch.github = "dgw/yourls-dont-track-admins"
src.git = "https://github.com/dgw/yourls-dont-track-admins.git"

[yourls-login-timeout]
fetch.github = "reanimus/yourls-login-timeout"
src.git = "https://github.com/reanimus/yourls-login-timeout.git"

[yourls-sleeky]
fetch.github = "Flynntes/Sleeky"
src.git = "https://github.com/Flynntes/Sleeky"
