[delegacy-rpz]
fetch.git = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git"
src.git = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git"

[firefox-translations-models]
fetch.github = "mozilla/firefox-translations-models"
git.fetchSubmodules = true # Force use fetchgit
src.git = "https://github.com/mozilla/firefox-translations-models.git"

[grafana-falconlogscale-datasource]
fetch.url = "https://github.com/grafana/falconlogscale-datasource/releases/download/v$ver/grafana-falconlogscale-datasource-$ver.zip"
src.github = "grafana/falconlogscale-datasource"
src.prefix = "v"

[grafana-yesoreyeram-infinity-datasource]
fetch.url = "https://github.com/grafana/grafana-infinity-datasource/releases/download/v$ver/yesoreyeram-infinity-datasource-$ver.zip"
src.github = "grafana/grafana-infinity-datasource"
src.prefix = "v"

[lobe-icons]
fetch.git = "https://github.com/lobehub/lobe-icons.git"
src.git = "https://github.com/lobehub/lobe-icons.git"

[mihoyo-bbs-tools]
fetch.github = "Womsxd/MihoyoBBSTools"
src.git = "https://github.com/Womsxd/MihoyoBBSTools.git"

[mpv-sockets]
fetch.github = "wis/mpvSockets"
src.git = "https://github.com/wis/mpvSockets.git"

[nvidia-patch]
fetch.github = "keylase/nvidia-patch"
src.git = "https://github.com/keylase/nvidia-patch.git"

[open5gs]
fetch.github = "open5gs/open5gs"
src.github = "open5gs/open5gs"

[open5gs-freediameter]
fetch.github = "open5gs/freeDiameter"
src.git = "https://github.com/open5gs/freeDiameter.git"
src.branch = "r1.5.0"

[openspeedtest]
fetch.github = "openspeedtest/Speed-Test"
src.git = "https://github.com/openspeedtest/Speed-Test.git"

[sakura-share]
fetch.github = "PiDanShouRouZhouXD/Sakura_Launcher_GUI"
src.git = "https://github.com/PiDanShouRouZhouXD/Sakura_Launcher_GUI.git"

[um-react]
fetch.url = "https://git.um-react.app/um/um-react/releases/download/v$ver/um-react-$ver.zip"
src.webpage = "https://git.um-react.app/um/um-react/releases"
src.regex = "href=\"/um/um-react/src/tag/v([0-9\\.]+)\""

[yourls]
fetch.github = "YOURLS/YOURLS"
src.github = "YOURLS/YOURLS"

[yourls-404-if-not-found]
fetch.github = "YOURLS/404-if-not-found"
src.git = "https://github.com/YOURLS/404-if-not-found.git"

[yourls-always-302]
fetch.github = "tinjaw/Always-302"
src.git = "https://github.com/tinjaw/Always-302.git"

[yourls-dont-track-admins]
fetch.github = "dgw/yourls-dont-track-admins"
src.git = "https://github.com/dgw/yourls-dont-track-admins.git"

[yourls-login-timeout]
fetch.github = "reanimus/yourls-login-timeout"
src.git = "https://github.com/reanimus/yourls-login-timeout.git"

[yourls-sleeky]
fetch.github = "Flynntes/Sleeky"
src.git = "https://github.com/Flynntes/Sleeky"
