[delegacy-rpz]
fetch.git = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git"
src.git = "https://codeberg.org/IPv6-Monostack/delegacy-rpz.git"

[grafana-falconlogscale-datasource]
fetch.url = "https://github.com/grafana/falconlogscale-datasource/releases/download/v$ver/grafana-falconlogscale-datasource-$ver.zip"
src.github = "grafana/falconlogscale-datasource"
src.prefix = "v"

[grafana-yesoreyeram-infinity-datasource]
fetch.url = "https://github.com/grafana/grafana-infinity-datasource/releases/download/v$ver/yesoreyeram-infinity-datasource-$ver.zip"
src.github = "grafana/grafana-infinity-datasource"
src.prefix = "v"

[lobe-icons]
fetch.git = "https://github.com/lobehub/lobe-icons.git"
src.git = "https://github.com/lobehub/lobe-icons.git"

[mihoyo-bbs-tools]
fetch.github = "Womsxd/MihoyoBBSTools"
src.git = "https://github.com/Womsxd/MihoyoBBSTools.git"

[mpv-sockets]
fetch.github = "wis/mpvSockets"
src.git = "https://github.com/wis/mpvSockets.git"

[nvidia-patch]
fetch.github = "keylase/nvidia-patch"
src.git = "https://github.com/keylase/nvidia-patch.git"

[open5gs]
fetch.github = "open5gs/open5gs"
src.github = "open5gs/open5gs"

[open5gs-freediameter]
fetch.github = "open5gs/freeDiameter"
src.git = "https://github.com/open5gs/freeDiameter.git"
src.branch = "r1.5.0"

[openspeedtest]
fetch.github = "openspeedtest/Speed-Test"
src.git = "https://github.com/openspeedtest/Speed-Test.git"

[sakura-share]
fetch.github = "PiDanShouRouZhouXD/Sakura_Launcher_GUI"
src.git = "https://github.com/PiDanShouRouZhouXD/Sakura_Launcher_GUI.git"

[ulauncher-albert-calculate-anything]
fetch.github = "tchar/ulauncher-albert-calculate-anything"
src.git = "https://github.com/tchar/ulauncher-albert-calculate-anything.git"

[ulauncher-colorconverter]
fetch.github = "sergius02/ulauncher-colorconverter"
src.git = "https://github.com/sergius02/ulauncher-colorconverter.git"

[ulauncher-emoji]
fetch.github = "Ulauncher/ulauncher-emoji"
src.git = "https://github.com/Ulauncher/ulauncher-emoji.git"

[ulauncher-kill]
fetch.github = "Ulauncher/ulauncher-kill"
src.git = "https://github.com/Ulauncher/ulauncher-kill.git"

[ulauncher-meme-my-text]
fetch.github = "RNairn01/ulauncher-meme-my-text"
src.git = "https://github.com/RNairn01/ulauncher-meme-my-text.git"

[ulauncher-tldr]
fetch.github = "dhelmr/ulauncher-tldr"
src.git = "https://github.com/dhelmr/ulauncher-tldr.git"

[ulauncher-virtualbox]
fetch.github = "luispabon/ulauncher-virtualbox"
src.git = "https://github.com/luispabon/ulauncher-virtualbox.git"

[ulauncher-vscode-recent]
fetch.github = "plibither8/ulauncher-vscode-recent"
src.git = "https://github.com/plibither8/ulauncher-vscode-recent.git"

[yourls]
fetch.github = "YOURLS/YOURLS"
src.github = "YOURLS/YOURLS"

[yourls-404-if-not-found]
fetch.github = "YOURLS/404-if-not-found"
src.git = "https://github.com/YOURLS/404-if-not-found.git"

[yourls-always-302]
fetch.github = "tinjaw/Always-302"
src.git = "https://github.com/tinjaw/Always-302.git"

[yourls-dont-track-admins]
fetch.github = "dgw/yourls-dont-track-admins"
src.git = "https://github.com/dgw/yourls-dont-track-admins.git"

[yourls-login-timeout]
fetch.github = "reanimus/yourls-login-timeout"
src.git = "https://github.com/reanimus/yourls-login-timeout.git"

[yourls-sleeky]
fetch.github = "Flynntes/Sleeky"
src.git = "https://github.com/Flynntes/Sleeky"
